[package]
name = "youtube_videos"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
csv = "1.3.0"
reqwest = {version = "0.12.9", features = ["json"] }
serde_json = "1.0.132"
tokio = { version = "1.41.1", features = ["full"] }
